config/routes.rb
    Bloccit::Application.routes.draw do

  get "comments/create"

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :topics do
    resources :posts, except: [:index] do
      resources :comments, only: [:create, :destroy]
    end
  end

  match "about" => 'welcome#about', via: :get

  root :to => 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_many :comments, dependent: :destroy
  belongs_to :user
  belongs_to :topic
  attr_accessible :body, :title, :topic, :image

  default_scope order('created_at DESC')

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment =Comment.new
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    authorize! :create, Post, message: "You need to be a member to create a new post."
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize! :edit, @post, message: "You need to own the post to edit it."
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(params[:post])
    @post.topic = @topic

    authorize! :create, @post, message: "You need to be signed up to do that."
    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])
    authorize! :update, @post, message: "You need to own the post to edit it."
    if @post.update_attributes(params[:post])
      flash[:notice] = "Post was updated."
      redirect_to [@topic, @post]
    else
      flash[:error] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @post = Post.find(params[:id])

    title = @post.title
    authorize! :destry, @post, message: "you need to own the post to delete it."
    if @post.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to @topic
    else
      flash[:error] = "There was an error deleting the post."
      render :show
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [topic, post], html: { class: 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :title %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :body, class: 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, rows: 8 %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.file_field :image %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">
      <%= f.submit "Save", class: 'btn' %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<div class="row">
  <div class="span4">
    <p>Guidelines for new posts:</p>
    <ul>
      <li>Make sure content is appropriate.</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
    </ul>
  </div>
  <div class="span6">
    <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="row">
  <div class="span4">
    <p>Guidelines for new posts:</p>
    <ul>
      <li>Make sure content is appropriate.</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
      <li>Blah blah blah</li>
    </ul>
  </div>
  <div class="span8">
    <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
  </div>
</div>

app/views/posts/show.html.erb
<h1><%= markdown @post.title %></h1>

<div class="row">
  <div class="span8">
    <small>
      <% image_tag(@post.user.avatar.tiny.url) if @post.user.avatar? %>
      submitted <% time_ago_in_words(@post.created_at) %> ago by
      <% @post.user.name %>
    </small>
    <p><%= markdown @post.body %></p>
    <%= image_tag @post.image_url if @post.image? %>

    <hr/>

    <h2><%= @comments.count %> Comments</h2>
    
    <%= render @comments %>
    
    <% if can? :create, Comment %>
      <hr/>
      <h4>New Comment</h4>
      <%= render partial: 'comments/form', locals: { topic: @topic, post: @post, comment: @comment } %>
    <% end %>

  </div>
  <div class="span4">
    <% if can? :edit, @post %>
      <%= link_to "Edit", edit_topic_post_path(@topic,@post), class: 'btn btn-large btn-block' %>
    <% end %>
    <% if can? :destroy, @post %>
    <%= link_to "Delete Post", [@topic, @post], method: :delete, class: 'btn-btn-large btn-block btn-danger', confirm: 'Are you sure you want to delete this post' %>
    <% end %>
  </div>
</div>